spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lmfood?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jackson:
    deserialization:
      fail-on-ignored-properties: true
      fail-on-unknown-properties: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8081
